### ISSUE TITLE
Debug package create new user home

### ISSUE THREAD

**Issue by himekifee** [coder/code-server-aur#8]
The debug package built with debug option enabled created two users home `/home/iojs` and `/home/vsts`. I don't think this is proper behaviour.

**Comment by jsjoeio** [comment]
I'm not super familiar with AUR or the debug package. Can you elaborate? (assume i know nothing)

**Comment by himekifee** [comment]
I'm also quite new to debug packages tbh. They just came out recently. Maybe we left it to somebody capable later.

**Comment by jsjoeio** [comment]
Since there isn't a specific action we can take on this, I'm going to close this.
